language: node_js
node_js:
  - '0.12.4'
before_script:
  - 'export CHROME_BIN=chromium-browser'
  - 'export DISPLAY=:99.0'
  - 'sh -e /etc/init.d/xvfb start'
  - 'npm install -g bower karma grunt-cli jshint codecov codeclimate-test-reporter'
  - 'npm install' # install npm packages
  - 'bower install' # install bower packages

after_script:
  - 'grunt default'
  - 'codecov coverage/cobertura/cobertura-coverage.xml --token=efbc6679-b12a-4f4b-8d73-6443566e0e0d'
  - 'CODECLIMATE_REPO_TOKEN=1cb32b39ff31ec40e538e2c5660d469905a579e57e3e9b86128a8e421f4a434d codeclimate-test-reporter < coverage/lcov/lcov.info'
