install:
  - choco install firefox
  - choco install googlechrome
  - ps: Install-Product node $env:nodejs_version
  - node --version
  - npm --version
   - npm install -g bower karma grunt-cli jshint
    - npm install
    - bower install


test_script:
  - grunt default
